openapi: "3.0.0"

info:
  title: ParcelWalaa API
  description: This is the documentation for ParcelWalaa API
  version: 1.0.0
  servers:
    - url: http://localhost:{port}/api_docs
      variables:
        port:
          - "3000"

tags:
  - name: Authentication
    description: Signin to the application
  - name: Shop
    description: Add/Update/Delete/Get shops

components:
  schemas:
    Error:
      type: object
      items:
        properties:
          status:
            type: string
            example: "sucess/fail"

          msg:
            type: string
            example: "Not found"

    Shop:
      type: object
      items:
        properties:
          image:
            type: string
            example: "adscsvf"

          banner:
            type: string
            example: "adcascdsd"

          number:
            type: integer
            example: 1234567890

          fssai:
            type: string
            example: "adcadc"

          admin_commission_rate:
            type: integer
            example: 4

          store_name:
            type: number
            example: macd

          email:
            type: string
            example: asxnakc@csd.com

          address_line1:
            type: string
            example: "acxacdadc"

          city:
            type: string
            example: "mumbai"

          state:
            type: string
            example: "maharashtra"

          delivery_charges:
            type: number
            example: 500

paths:
  /auth/send_otp:
    post:
      tags:
        - Authentication
      summary: Provides opt for signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - number
              properties:
                number:
                  type: integer
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    msg:
                      type: string
                      example: "Otp sent sucessfully"

                    status:
                      type: string
                      example: "sucess"

                    number:
                      type: integer
                      example: 1234567890

                    code:
                      type: integer
                      example: 121324
        404:
          description: Fail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/verify_otp:
    post:
      tags:
        - Authentication
      summary: Verify opt for signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - number
                - otpCode
              properties:
                number:
                  type: integer
                otpCode:
                  type: string
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    msg:
                      type: string
                      example: "Otp sent sucessfully"

                    status:
                      type: string
                      example: "sucess"

                    number:
                      type: integer
                      example: 1234567890

                    code:
                      type: integer
                      example: 121324

        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

        404:
          description: Fail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /shop/add_shop:
    post:
      tags:
        - Shop
      summary: Adds shop (admin)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                properties:
                  number:
                    type: integer
                    example: 1234567890

                  fssai:
                    type: string
                    example: "adcadc"

                  admin_commission_rate:
                    type: integer
                    example: 4

                  store_name:
                    type: number
                    example: macd

                  email:
                    type: string
                    example: asxnakc@csd.com

                  address_line1:
                    type: string
                    example: "acxacdadc"

                  city:
                    type: string
                    example: "mumbai"

                  state:
                    type: string
                    example: "maharashtra"
                    
                  delivery_charges:
                    type: number
                    example: 500
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Shop"

        404:
          description: Fail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
