openapi: "3.0.0"

info:
  title: ParcelWalaa API
  description: This is the documentation for ParcelWalaa API
  version: 1.0.0
  servers:
    - url: http://localhost:{port}/api_docs
      variables:
        port:
          - "3000"

tags:
  - name: Authentication
    description: Signin to the application
  - name: Shop
    description: Add/Update/Delete/Get shops
  - name: Cart
    description: Cart

components:
  schemas:
    Error:
      type: object
      items:
        properties:
          status:
            type: string
            example: "sucess/fail"

          msg:
            type: string
            example: "Not found"

    Shop:
      type: object
      items:
        required:
          - image
          - banner
          - number
          - fssai
          - admin_commission_rate
          - store_name
          - email
          - address_line1
          - city
          - state
          - delivery_charges
        properties:
          image:
            type: string
            example: "adscsvf"

          banner:
            type: string
            example: "adcascdsd"

          number:
            type: integer
            example: 1234567890

          fssai:
            type: string
            example: "adcadc"

          admin_commission_rate:
            type: integer
            example: 4

          store_name:
            type: number
            example: macd

          email:
            type: string
            example: asxnakc@csd.com

          address_line1:
            type: string
            example: "acxacdadc"

          city:
            type: string
            example: "mumbai"

          state:
            type: string
            example: "maharashtra"

          delivery_charges:
            type: number
            example: 500

    Cart:
      type: object
      items:
        required:
          - inventory_total_amt
          - delivery_total_amt
          - coupon_code_id
          - discount_amt
          - delivery_address_id
          - net_amt
          - shop_id
          - cart_inventory
          - total_gst
          - user_id
        properties:
          inventory_total_amt:
            type: integer
          delivery_total_amt:
            type: integer
          coupon_code_id:
            type: string
          discount_amt:
            type: integer
          admin_commission_rate:
            type: integer
            example: 4
          delivery_address_id:
            type: string
          net_amt:
            type: integer
          shop_id:
            type: string
          cart_inventory:
            type: string
          total_gst:
            type: integer
          user_id:
            type: string

paths:
  /auth/send_otp:
    post:
      tags:
        - Authentication
      summary: Provides opt for signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - number
              properties:
                number:
                  type: integer
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    msg:
                      type: string
                      example: "Otp sent sucessfully"

                    status:
                      type: string
                      example: "sucess"

                    number:
                      type: integer
                      example: 1234567890

                    code:
                      type: integer
                      example: 121324
        404:
          description: Fail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/verify_otp:
    post:
      tags:
        - Authentication
      summary: Verify opt for signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - number
                - otpCode
              properties:
                number:
                  type: integer
                otpCode:
                  type: string
      responses:
        200:
          description: Sucess

          content:
            application/json:
              schema:
                type: object
                items:
                  properties:
                    msg:
                      type: string
                      example: "Otp sent sucessfully"

                    status:
                      type: string
                      example: "sucess"

                    number:
                      type: integer
                      example: 1234567890

                    code:
                      type: integer
                      example: 121324
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: Fail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /shop/add_shop:
    post:
      tags:
        - Shop
      summary: Adds shop (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                properties:
                  $ref: "#/components/schemas/Shop"
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Shop"
        404:
          description: Fail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /shop/update_shop:
    put:
      tags:
        - Shop
      summary: Updates the shop (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                properties:
                  $ref: "#/components/schemas/Shop"
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Shop"
        404:
          description: Fail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /shop/delete_shop:
    delete:
      tags:
        - Shop
      summary: Delete the shop (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                properties:
                  number:
                    type: integer
                    example: 1234567890
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Shop"

  /shop/get_shops:
    get:
      tags:
        - Shop
      summary: Retrive all the shops (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Shop"

  /shop/store_status_update:
    post:
      tags:
        - Shop
      summary: Store status update (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                properties:
                  number:
                    type: integer
                    example: 1234567890

                  isOnline:
                    type: boolean
                    example: true/false
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Shop"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /shop/store_admin_status_update:
    post:
      tags:
        - Shop
      summary: Store admin status update (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                properties:
                  number:
                    type: integer
                    example: 1234567890

                  isActive:
                    type: boolean
                    example: true/false
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Shop"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /cart/add_cart:
    post:
      tags:
        - Cart
      summary: Add to cart (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                properties:
                  productId:
                    type: string
                  delivery_address_id:
                    type: string
                  coupon_code_id:
                    type: string
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /cart/get_cart:
    get:
      tags:
        - Cart
      summary: Get all the carts (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /cart/remove_cart:
    delete:
      tags:
        - Cart
      summary: Delete the cart (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /cart/update_cart:
    put:
      tags:
        - Cart
      summary: Update the cart (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /cart/update_qty:
    put:
      tags:
        - Cart
      summary: Update the cart (admin)
      parameters:
        - in: header
          name: token
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              items:
                properties:
                  productId:
                    type: string
                  quantity:
                    type: integer
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
